# Generated by Django 6.0 on 2026-01-29 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_embeddingcall_aicall_model"),
        ("chat", "0002_messageembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="embedding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ai.embeddingcall",
            ),
        ),
        migrations.DeleteModel(
            name="MessageEmbedding",
        ),
    ]
