# Generated by Django 6.0 on 2026-01-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_message_embedding_delete_messageembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
