# Generated by Django 6.0 on 2026-01-31 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_conversation_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="user_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="chat.message",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="messages",
                to="chat.conversation",
            ),
        ),
    ]
