# Generated by Django 6.0 on 2026-02-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_message_user_message_alter_message_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_error",
            field=models.BooleanField(default=False),
        ),
    ]
