# Generated by Django 6.0 on 2026-02-06 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_aicall_is_error"),
        ("chat", "0006_message_is_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="ai_call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="conversations",
                to="ai.aicall",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="ai_call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="messages",
                to="ai.aicall",
            ),
        ),
    ]
