# Generated by Django 6.0 on 2026-01-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_reader", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billsubtransaction",
            name="bill",
        ),
        migrations.DeleteModel(
            name="Bill",
        ),
        migrations.DeleteModel(
            name="BillSubTransaction",
        ),
    ]
