# Generated by Django 6.0 on 2026-01-29 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("file_reader", "0002_remove_billsubtransaction_bill_delete_bill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="ai_call",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="ai.aicall"
            ),
        ),
        migrations.DeleteModel(
            name="AICall",
        ),
    ]
