# Generated by Django 6.0 on 2026-02-06 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_aicall_is_error"),
        ("file_reader", "0004_file_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="ai_call",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="ai.aicall",
            ),
        ),
    ]
