# Generated by Django 6.0 on 2026-05-19 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("file_reader", "0005_alter_file_ai_call"),
        ("transactions", "0014_subtransaction_category_transaction_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("principal_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("lent_at", models.DateField()),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("settled", "Quitado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="transactions.actor",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_loans",
                        to="file_reader.file",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-lent_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid_at", models.DateField()),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_payments",
                        to="file_reader.file",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at"],
            },
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["actor"], name="loans_loan_actor_i_be1416_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["status"], name="loans_loan_status_962e99_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["lent_at"], name="loans_loan_lent_at_aecfa1_idx"),
        ),
        migrations.AddIndex(
            model_name="loanpayment",
            index=models.Index(fields=["loan", "paid_at"], name="loans_loanp_loan_id_da9c7c_idx"),
        ),
        migrations.AddConstraint(
            model_name="loanpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("file__isnull", False)),
                fields=("file",),
                name="unique_active_file_per_loan_payment",
            ),
        ),
    ]
