# Generated by Django 6.0 on 2026-02-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
