# Generated by Django 5.2.14 on 2026-09-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='modo_on',
            field=models.BooleanField(default=False),
        ),
    ]
