# Generated by Django 5.2.14 on 2026-09-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_profile_modo_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='salary_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
