# Generated by Django 5.2.14 on 2026-09-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_profile_salary_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_essentials_goal',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_savings_goal',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_spending_goal',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
