# Generated by Django 6.0 on 2026-01-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AICall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt", models.JSONField()),
                ("response", models.JSONField()),
                ("total_tokens", models.IntegerField()),
                ("input_used_tokens", models.IntegerField()),
                ("output_used_tokens", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
