# Generated by Django 6.0 on 2026-01-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicall",
            name="response_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
