# Generated by Django 6.0 on 2026-01-29 06:39

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_aicall_response_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("model", models.CharField(max_length=255)),
                ("total_tokens", models.IntegerField()),
                ("prompt_used_tokens", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="aicall",
            name="model",
            field=models.CharField(default="gemini-2.5-flash-lite", max_length=255),
            preserve_default=False,
        ),
    ]
