# Generated by Django 6.0 on 2026-02-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_embeddingcall_aicall_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicall",
            name="is_error",
            field=models.BooleanField(default=False),
        ),
    ]
