# Generated by Django 6.0 on 2026-01-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_salary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                default="outgoing",
                max_length=255,
            ),
        ),
    ]
