# Generated by Django 6.0 on 2026-01-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_actor_user_transaction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_recurrent",
            field=models.BooleanField(default=False),
        ),
    ]
