# Generated by Django 6.0 on 2026-01-14 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_transaction_is_recurrent"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="installment_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="main_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recurrence_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
