# Generated by Django 6.0 on 2026-01-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_transaction_installment_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtransaction",
            name="user_provided_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
