# Generated by Django 6.0 on 2026-01-28 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_subtransaction_user_provided_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtransaction",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transactions.actor",
            ),
        ),
    ]
