# Generated by Django 6.0 on 2026-01-30 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_actor_deleted_at_subtransaction_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtransaction",
            name="installment_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="subtransaction",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_transactions",
                to="transactions.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="main_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installments",
                to="transactions.transaction",
            ),
        ),
    ]
