# Generated by Django 6.0 on 2026-02-01 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_reader", "0004_file_user"),
        ("transactions", "0009_alter_subtransaction_installment_info_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-due_date"]},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["due_date"], name="transaction_due_dat_507052_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_identifier"], name="transaction_transac_927ff7_idx"
            ),
        ),
    ]
