# Generated by Django 6.0 on 2026-02-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtransaction",
            name="paid_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="paid_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
