# Generated by Django 6.0 on 2026-02-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0012_subtransaction_category_transaction_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subtransaction",
            name="category",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="category",
        ),
    ]
