# Generated by Django 5.2.14 on 2026-09-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseintention',
            name='installments',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
